services:
  client:
    image: burakkutluk/ai-client:latest
    ports:
      - "3000:3000"
    restart: always

  server:
    image: burakkutluk/ai-server:latest
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PORT=5000