apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-image-generator
  namespace: argocd
spec:
  destination:
    namespace: ai-image-generator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/burakkutluk/AI-image-generator
    targetRevision: HEAD
    path: k8s
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
